spring:
    datasource:
        driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
        jdbc-url: 'jdbc:sqlserver:'
        username: ''
        password: ''
    jpa:
        properties:
            hibernate:
                #dialect: 'org.hibernate.dialect.SQLServerDialect'
                ## Tambah property ini supaya bisa paging, untuk hibernate < 6.0.0 atau springboot < 3.0.0
                legacy_limit_handler: true

config:
    audit:
        datasource:
            driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
            jdbc-url: 'jdbc:sqlserver:'
            username: ''
            password: ''
        jpa:
            properties:
                hibernate:
                    #dialect: 'org.hibernate.dialect.SQLServerDialect'
                    legacy_limit_handler: true

other:
    trxManager:
        second:
            datasource:
                driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
                jdbc-url: 'jdbc:sqlserver:'
                username: ''
                password: ''
            jpa:
                properties:
                    hibernate:
                        #dialect: 'org.hibernate.dialect.SQLServerDialect'
                        legacy_limit_handler: true
            audit:
                datasource:
                    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
                    jdbc-url: 'jdbc:sqlserver:'
                    username: ''
                    password: ''
                jpa:
                    properties:
                        hibernate:
                            #dialect: 'org.hibernate.dialect.SQLServerDialect'
                            legacy_limit_handler: true
