server:
   port: 5401
      
debug: false

management:
   endpoints:
      web:
         exposure:
            include: "*"

spring:
   application:
      name: ideahut-springboot-2x-template-mvc
   quartz:
      auto-startup: false
   servlet:
      multipart:
         max-file-size: 256MB
         max-request-size: 256MB
   main:
      banner-mode: "off"
   
      
   #
   # Ganti profile sesuai dengan database yang digunakan
   #
   profiles:
      #active: "db2"
      #active: "derby"
      #active: "h2"
      #active: "hsql"
      #active: "mariadb"
      active: "mysql"
      #active: "oracle"
      #active: "postgresql"
      #active: "sqlserver"

   datasource:
      hikari:
         connection-timeout: "10000"
         minimum-idle: "10"
         maximum-pool-size: "10"
         idle-timeout: "5000"
         max-lifetime: "1000"
         auto-commit: "true"
         
   jpa:
      open-in-view: false
      properties:
         hibernate:
            hbm2ddl:
               auto: update
               #auto: none
            show_sql: true
            #generate_statistics: true
            audit_identifier: spring_sample_main
            audit_bean_name: mainAuditSessionFactory

app:
   waitAllBeanConfigured: true
   loggingError: true
   autoStartScheduler: false
   messagePath: "file:{user.dir}/extras/message/"
   reportPath: "file:{user.dir}/extras/report/"
   
   #
   # CORS Http Header
   #
   cors:
      "Access-Control-Allow-Credentials": "true"
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "*"
      "Access-Control-Max-Age": "360"
      "Access-Control-Allow-Headers": "*"
      "Access-Control-Expose-Headers": "*"
                     
   ignored-handler-classes:
      - org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController
      - org.springframework.web.servlet.NoHandlerFoundException
   
   #
   # Model / Entity yang punya annotation @ForeignKeyEntity akan dieksekusi
   # Beberapa database tidak support "... on update (CASCADE/SET_NULL)"
   #
   foreignKey:
      enableExecution: true
      dropBeforeCreate: true
      onUpdateAction: true 
      
   audit:
      jpa:
         properties:
            hibernate:
               show_sql: true
               #generate_statistics: true
      properties:
         generate:
            table: true
         enable:
            audit: true
         #table:
         #   index: false   
   
   task:      
      common:
         threadNamePrefix: "TASK-COMMON"
         corePoolSize: 2
         maxPoolSize: 8
         waitForJobsToCompleteOnShutdown: true
         allowCoreThreadTimeOut: true
      audit:
         threadNamePrefix: "TASK-AUDIT"
         corePoolSize: 2
         maxPoolSize: 8
         waitForJobsToCompleteOnShutdown: true
         allowCoreThreadTimeOut: true

   redis:
      common:
         type: 1
         testOnStartup: true
         standalone:
            host: ""
            port: ""
            password: ""
            database: 0
            
   cache:
      groups:
         - name: TEST1
           limit: 20
           expiry: 
              unit: SECONDS
              value: 3600
           nullable: true
         - name: TEST2
           limit: -1
           expiry: 
              unit: SECONDS
              value: 0
           nullable: true

   mail:
      host: smtp.gmail.com
      port: 587
      username: ""
      password: ""
      properties:
         "mail.smtp.host": "smtp.gmail.com"
         "mail.smtp.ssl.trust": "smtp.gmail.com"
         "mail.smtp.port": "587"
         "mail.smtp.auth": "true"
         "mail.smtp.starttls.enable": "true"
         "mail.imap.ssl.enable": "true"
         "mail.transport.protocol": "smtp"
         "mail.debug": "true"
         "mail.smtp.ssl.protocols": "TLSv1.2"
         
   grid:
      location: "file:{user.dir}/extras/grid/**/*.json"
      #definition: "file:{user.dir}/extras/grid/grid.def"
      
   admin:
      configFile: "file:{user.dir}/extras/admin/config.json"
      credentialFile: "file:{user.dir}/extras/admin/credential-bcrypt.json"
      #credentialFile: "file:{user.dir}/extras/admin/credential-sha256.json"
      
   api:
      enable:
         consumer: true
         crud: true
         sync: true
      consumer:
         secret: "df7c7d71-ec05-4ad4-9b36-1580b1a6590f"
         digest: "SHA-256"
         expiry: 
            unit: SECONDS
            value: 86400 # 1 hari
      jwtProcessor:
         secret: "77ea06ac-808b-4399-895c-a546b033d533"
         digest: "SHA-256"
         expiry: 
            unit: SECONDS
            value: 3600 # 1jam
      redisExpiry:
         timeUnit: SECONDS
         accessNull: 120
         accessItem: 300
         consumerNull: 120
         consumerItem: 600
      ## toleransi waktu atas/bawah timestamp
      signatureTimeSpan: 
         unit: SECONDS
         value: 60
      defaultDigest: "SHA-256"
   
   webAsync:
      threadNamePrefix: "WEB-ASYNC"
      corePoolSize: 10
      maxPoolSize: 100

other:   
   trxManager:
      second:
         jpa:
            properties:
               hibernate:
                  hbm2ddl:
                     auto: update
                  show_sql: true
                  audit_identifier: spring_sample_other
                  audit_bean_name: otherAuditSessionFactory
         audit:
            jpa:
               properties:
                  hibernate:
                     show_sql: true
            properties:
               generate:
                  table: true
               enable:
                  audit: true
               table:
                  index: false
             
logging:
   file:
      name: "./logs/ideahut-springboot-2x-template-mvc.log"
   pattern:
      console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
      file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
   level:
      org:
         hibernate: INFO
         springframework: INFO
      redis:
         clients:
            jedis:
               JedisFactory: OFF
      com:
         fasterxml:
            jackson:
               dataformat:
                  xml: OFF
         zaxxer:
            hikari:
               pool:
                  ProxyConnection: ERROR
      net:
         ideahut:
            springboot:
               bean: DEBUG
