spring:
    datasource:
        driver-class-name: 'org.apache.derby.jdbc.ClientDriver'
        jdbc-url: 'jdbc:derby:'
        username: ''
        password: ''
    jpa:
        properties:
            hibernate:
                #dialect: 'org.hibernate.dialect.DerbyDialect'
                jdbc:
                    lob:
                        non_contextual_creation: true

config:
    audit:
        datasource:
            driver-class-name: 'org.apache.derby.jdbc.ClientDriver'
            jdbc-url: 'jdbc:derby:'
            username: ''
            password: ''
        jpa:
            properties:
                hibernate:
                    #dialect: 'org.hibernate.dialect.DerbyDialect'
                    jdbc:
                        lob:
                            non_contextual_creation: true

other:
    trxManager:
        second:
            datasource:
                driver-class-name: 'org.apache.derby.jdbc.ClientDriver'
                jdbc-url: 'jdbc:derby:'
                username: ''
                password: ''
            jpa:
                properties:
                    hibernate:
                        #dialect: 'org.hibernate.dialect.DerbyDialect'
                        jdbc:
                            lob:
                                non_contextual_creation: true
            audit:
                datasource:
                    driver-class-name: 'org.apache.derby.jdbc.ClientDriver'
                    jdbc-url: 'jdbc:derby:'
                    username: ''
                    password: ''
                jpa:
                    properties:
                        hibernate:
                            #dialect: 'org.hibernate.dialect.DerbyDialect'
                            jdbc:
                                lob:
                                    non_contextual_creation: true
