spring:  
   datasource:
      driver-class-name: "com.ibm.db2.jcc.DB2Driver"
      jdbc-url: "jdbc:db2://localhost:50000/sample"
      username: "<username>"
      password: "<password>"
   #jpa:
      #properties:
         #hibernate:
            #dialect: "org.hibernate.dialect.DB2Dialect"
            
app:
   audit:
      datasource:
         driver-class-name: "com.ibm.db2.jcc.DB2Driver"
         jdbc-url: "jdbc:db2://localhost:50001/audit"
         username: "<username>"
         password: "<password>"   
      #jpa:
         #properties:
            #hibernate:
               #dialect: "org.hibernate.dialect.DB2Dialect"
